// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace WEB_PROJEKAT.Migrations
{
    [DbContext(typeof(AzilContext))]
    [Migration("20220105112321_V10")]
    partial class V10
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Models.Azil", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("BrojPasa")
                        .HasColumnType("int");

                    b.Property<string>("Grad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kapacitet")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PostanskiBroj")
                        .HasColumnType("int");

                    b.Property<string>("Ulica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Azil");
                });

            modelBuilder.Entity("Models.Pas", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Ime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Pol")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("Starost")
                        .HasColumnType("int");

                    b.Property<int>("Tezina")
                        .HasColumnType("int");

                    b.Property<int>("Velicina")
                        .HasColumnType("int");

                    b.Property<int?>("azilID")
                        .HasColumnType("int");

                    b.Property<DateTime>("datum_rodjenja")
                        .HasColumnType("datetime2");

                    b.Property<int?>("rasaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("azilID");

                    b.HasIndex("rasaID");

                    b.ToTable("Psi");
                });

            modelBuilder.Entity("Models.Rasa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Naziv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Rase");
                });

            modelBuilder.Entity("Models.Udomitelj", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Grad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PostanskiBroj")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ulica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("azilID")
                        .HasColumnType("int");

                    b.Property<int?>("pasID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("azilID");

                    b.HasIndex("pasID");

                    b.ToTable("Udomitelji");
                });

            modelBuilder.Entity("Models.Pas", b =>
                {
                    b.HasOne("Models.Azil", "azil")
                        .WithMany("psi")
                        .HasForeignKey("azilID");

                    b.HasOne("Models.Rasa", "rasa")
                        .WithMany("psi")
                        .HasForeignKey("rasaID");

                    b.Navigation("azil");

                    b.Navigation("rasa");
                });

            modelBuilder.Entity("Models.Udomitelj", b =>
                {
                    b.HasOne("Models.Azil", "azil")
                        .WithMany("udomitelji")
                        .HasForeignKey("azilID");

                    b.HasOne("Models.Pas", "pas")
                        .WithMany()
                        .HasForeignKey("pasID");

                    b.Navigation("azil");

                    b.Navigation("pas");
                });

            modelBuilder.Entity("Models.Azil", b =>
                {
                    b.Navigation("psi");

                    b.Navigation("udomitelji");
                });

            modelBuilder.Entity("Models.Rasa", b =>
                {
                    b.Navigation("psi");
                });
#pragma warning restore 612, 618
        }
    }
}
